# Generated by Django 3.0.6 on 2020-08-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200830_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='pic',
            field=models.ImageField(blank=True, upload_to='goods/'),
        ),
    ]
