# Generated by Django 3.0.6 on 2020-09-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200830_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(verbose_name='Price in RUR'),
        ),
    ]
