# Generated by Django 3.0.6 on 2020-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200919_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_options',
            field=models.CharField(blank=True, choices=[('C', 'Courier'), ('P', 'Pickup')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.IntegerField(blank=True, choices=[(1, 'Moscow State University'), (2, 'Cosmos Hotel'), (3, 'Gorod Mall')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
